const mockuplistcard = [
  {
    img: "/src/image/listplay/game/listplayTalon.png",
    logo: "/src/image/logo/Talon.png",
    name: "TALON Valorant",
    caption: "ถ้าเจอหมด ก็เล่นได้หมด | Flight Club 5",
    time: "1 ชั่วโมงที่ผ่านมา",
    watch: "การดู 5.3 พัน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/คำต้องเชื่อมEP84.png",
    logo: "/src/image/logo/ยกกำลัง.png",
    name: "ยกกำลัง",
    caption: "คำต้องเชื่อม EP.84 | ยกกำลัง",
    time: "2 เดือนที่ผ่านมา",
    watch: "การดู 5.3 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/คำต้องเชื่อมEP94.png",
    logo: "/src/image/logo/ยกกำลัง.png",
    name: "ยกกำลัง",
    caption: "คำต้องเชื่อม EP.94 | ยกกำลัง",
    time: "1 เดือนที่ผ่านมา",
    watch: "การดู 2.3 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/SoundsFashy.png",
    logo: "/src/image/logo/RUBSHRB.jpg",
    name: "RUBSHRB",
    caption: "ปลากฏว่า เรื่องนี้จริงใช่ไหม : SOUNDS FISHY",
    time: "4 เดือนที่ผ่านมา",
    watch: "การดู 9.1 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/Q&AEP19.png",
    logo: "/src/image/logo/OHANA.jpg",
    name: "Ohana clip",
    caption: "Q&A รีววยหัวคิว EP.19 : ดอกไม้กินได้",
    time: "1 วันที่ผ่านมา",
    watch: "การดู 4.4 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/ขั้นเขา3000ขั้น.png",
    logo: "/src/image/logo/RUBSHRB.jpg",
    name: "RUBSHRB",
    caption: "พิชิตเขาวงพระจันทร์ 3000 ชั้น++ กับบท สรุปเรื่องผีของต้นกล้า",
    time: "1 ปีที่แล้ว",
    watch: "การดู 6.9 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/game/หมูป่า.png",
    logo: "/src/image/logo/HRK.jpg",
    name: "HERRTROCKER",
    caption: "ขอบคุณมากฮะ พี่หมูป่า - สายด่วนป่วน FREE FIRE #22",
    time: "9 เดือนที่ผ่านมา",
    watch: "การดู 5.3 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/werewolfEP.14.png",
    logo: "/src/image/logo/เทพลีลา.jpg",
    name: "เทพลีลา",
    caption:
      "Werewolf คืนหอนหลอนหมาป่า EP.14 | เทพลีลา X บาส @BBMemory โบร์ @Bowkanyaratp",
    time: "1 เดือนที่ผ่านมา",
    watch: "การดู 9.1 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/ข้างกัน.png",
    logo: "/src/image/logo/Three man down.png",
    name: "ThreeManDownOfficial",
    caption:
      "Three Man Down - ข้างกัน (City) Feat.ออม TELEx TELEXs「Official Video」",
    time: "6 ปีที่แล้ว",
    watch: "การดู 131 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/อะไรอยู่บนหัว.png",
    logo: "/src/image/logo/RUBSHRB.jpg",
    name: "RUBSHRB",
    caption: "โจทย์โหดเหมือนโกรธเป็ดถีบ [อะไรอยู่บนหัวกูวะ ... EP.4]",
    time: "2 เดือนที่ผ่านมา",
    watch: "การดู 5.4 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/อยู่กับฉันก่อน.png",
    logo: "/src/image/logo/Saran.jpg",
    name: "SARAN",
    caption:
      "SARAN - อยู่กับฉันก่อน ft. THAOWANZ [HIDDEN WORLD - LIVE SESSION]",
    time: "4 เดือนที่ผ่านมา",
    watch: "การดู 3.6 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/ใจพัง.png",
    logo: "/src/image/logo/Saran.jpg",
    name: "SARAN",
    caption: "SARAN - ใจพัง ft. GTK [HIDDEN WORLD - LIVE SESSION]",
    time: "7 เดือนที่ผ่านมา",
    watch: "การดู 7.6 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/blackpanther.png",
    logo: "/src/image/logo/VRZO.jpg",
    name: "VRZOchannel",
    caption: "ช๊อคทั้งโลก!! ฝ่าบาททีชัลล่า แบล็คแพนเธอร์ เสียชีวิตแล้ว | VRZO",
    time: "3 ปีที่แล้ว",
    watch: "การดู 4.9 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/หูหนวกทายคำ.png",
    logo: "/src/image/logo/OHANA.jpg",
    name: "Ohana clip",
    caption: "OHANA บ้าพลัง EP.73 : หูหนวกทายปาก V3",
    time: "7 เดือนที่ผ่านมา",
    watch: "การดู 1.7 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/comedy/ที่เป็นเรา.png",
    logo: "/src/image/logo/VRZO.jpg",
    name: "VRZOchannel",
    caption: "นิทานเรื่อง “ที่เป็นเรา” | VRZO",
    time: "2 ปีที่แล้ว",
    watch: "การดู 1.7 แสน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/คิด(แต่ไม่)ถึง.png",
    logo: "/src/image/logo/Three man down.png",
    name: "ThreeManDownOfficial",
    caption:
      "คิด(แต่ไม่)ถึง x ฝนตกไหม - Three Man Down Live เพลงสามัญประจำบ้าน",
    time: "3 ปีที่แล้ว",
    watch: "การดู 8.7 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/คิดฮอด7ZGTREMIX.png",
    logo: "/src/image/logo/7ZGT.jpg",
    name: "7ZGT",
    caption:
      "Bodyslam ft. 1Mill, Fiixd, Ben Bizzy, & Younggu - คิดฮอด (7ZGT REMIX)",
    time: "3 ปีที่แล้ว",
    watch: "การดู 5.7 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/ทุ้มอยู่ในใจ.png",
    logo: "/src/image/logo/GTHchannel.jpg",
    name: "GTHchannel",
    caption: "MV ทุ้มอยู่ในใจ (Official MV)",
    time: "6 ปีที่แล้ว",
    watch: "การดู 12 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/ผู้ชายไม่เป็นเพื่อนกับผู้หญิง.png",
    logo: "/src/image/logo/Three man down.png",
    name: "ThreeManDownOfficial",
    caption:
      "Three Man Down - ผู้ชายไม่เป็นเพื่อนกับผู้หญิง (Cover)「Original by กอล์ฟ & ไมค์」",
    time: "3 ปีที่แล้ว",
    watch: "การดู 15 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/ส่งเธอได้เท่านี้.png",
    logo: "/src/image/logo/lomosonicofficial.png",
    name: "lomosonicofficial",
    caption:
      "ส่งเธอได้เท่านี้ (GOODBYE) FEAT. K6Y - LOMOSONIC [ALBUM LAUNCH SESSION]",
    time: "1 ปีที่แล้ว",
    watch: "การดู 10.5 ล้าน ครั้ง",
  },
  {
    img: "/src/image/listplay/music/เพลงที่เธอไม่ฟัง.png",
    logo: "/src/image/logo/TERO MUSIC.png",
    name: "TERO MUSIC",
    caption: "Bedroom Audio - เพลงที่เธอไม่ฟัง [Official Music Video]",
    time: "2 ปีที่แล้ว",
    watch: "การดู 3.5 ล้าน ครั้ง",
  },
];
export default mockuplistcard;
